// generated by stringer -type=Major; DO NOT EDIT

package cbor

import "fmt"

const _Major_name = "cborUnsignedIntcborNegativeIntcborByteStringcborTextStringcborDataArraycborDataMapcborTagcborNC"

var _Major_index = [...]uint8{0, 15, 30, 44, 58, 71, 82, 89, 95}

func (i Major) String() string {
	if i+1 >= Major(len(_Major_index)) {
		return fmt.Sprintf("Major(%d)", i)
	}
	return _Major_name[_Major_index[i]:_Major_index[i+1]]
}
